#!/bin/bash
service = (di sini bisa diganti dengan nama services, misal: odoo-server)

if (( $(ps -ef | grep -v grep | grep $service | wc -l) > 0 ))
then
echo "$service is running!!!"
else
/etc/init.d/$service start
fi
